name: Create Docker Network

on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@v1
        env:
          INPUT_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          INPUT_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          INPUT_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: INPUT_POSTGRES_PASSWORD,INPUT_POSTGRES_USER,INPUT_POSTGRES_DB
          script: |
            echo "--- Create Docker Network ---"
            docker network create airbelgie